apiVersion: v1
data:
  mapAccounts: |
    []
  mapRoles: |
    - "groups":
      - "system:bootstrappers"
      - "system:nodes"
      "rolearn": "arn:aws:iam::712751870152:role/my-cluster2022040315184999720000000b"
      "username": "system:node:{{EC2PrivateDNSName}}"
  mapUsers: |
      - "userarn": "arn:aws:iam::712751870152:user/kube-cluster-admin"
        " username": "kube-cluster-admin"
         "groups":
           - "system:masters"
  mapRoles: |
   - "rolearn": "arn:aws:iam::712751870152:user/kube-cluster-admin"
     "username": "kube-cluster-admin"
     "groups":
       - "system:masters"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-03T15:18:52Z"
  labels:
    app.kubernetes.io/managed-by: Terraform
    terraform.io/module: terraform-aws-modules.eks.aws
  name: aws-auth
  namespace: kube-system
  resourceVersion: "619"
  uid: cd5de5f9-5484-45df-97ec-503e49a27627
